sudo: required
language: python
services:
  - docker
env:
  global:
    - DOCKER_REPO=article
    - EB_REGION="us-east-1"
before_install:
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
  - docker build -t $DOCKER_REPO ./services/article
deploy:
  provider: script
  script: bash ./travis-scripts/docker_push.sh
  on:
    all_branches: true
