// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/article/article.proto

package my_fridge_service_article

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ArticleService service

func NewArticleServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ArticleService service

type ArticleService interface {
	CreateArticle(ctx context.Context, in *Article, opts ...client.CallOption) (*Response, error)
	GetArticles(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error)
}

type articleService struct {
	c    client.Client
	name string
}

func NewArticleService(name string, c client.Client) ArticleService {
	return &articleService{
		c:    c,
		name: name,
	}
}

func (c *articleService) CreateArticle(ctx context.Context, in *Article, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ArticleService.CreateArticle", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleService) GetArticles(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ArticleService.GetArticles", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ArticleService service

type ArticleServiceHandler interface {
	CreateArticle(context.Context, *Article, *Response) error
	GetArticles(context.Context, *GetRequest, *Response) error
}

func RegisterArticleServiceHandler(s server.Server, hdlr ArticleServiceHandler, opts ...server.HandlerOption) error {
	type articleService interface {
		CreateArticle(ctx context.Context, in *Article, out *Response) error
		GetArticles(ctx context.Context, in *GetRequest, out *Response) error
	}
	type ArticleService struct {
		articleService
	}
	h := &articleServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ArticleService{h}, opts...))
}

type articleServiceHandler struct {
	ArticleServiceHandler
}

func (h *articleServiceHandler) CreateArticle(ctx context.Context, in *Article, out *Response) error {
	return h.ArticleServiceHandler.CreateArticle(ctx, in, out)
}

func (h *articleServiceHandler) GetArticles(ctx context.Context, in *GetRequest, out *Response) error {
	return h.ArticleServiceHandler.GetArticles(ctx, in, out)
}
